import logger from '../util/logger';
import { getSelectors } from './selectors';
import * as clientManaged from './client-managed';
import * as cloud from './cloud';

/**
 * Platform detection and adapter routing.
 *
 * Both adapters are statically imported so the Rollup UMD bundle
 * remains a single file (no dynamic code-splitting).
 */

/**
 * Detect the current platform type from the URL.
 * This is synchronous — it does NOT fetch the Sense version.
 *
 * @returns {'client-managed' | 'cloud'} Platform type.
 */
export function detectPlatformType() {
    const url = window.location.href;
    const isCloud = /qlikcloud\.com/i.test(url) || /\.qlik\.com\/sense/i.test(url);
    return isCloud ? 'cloud' : 'client-managed';
}

/**
 * Detect the current platform, including Sense version for client-managed.
 *
 * For client-managed, this fetches `/resources/autogenerated/product-info.js`
 * to determine the exact Sense version and resolve the correct code path.
 *
 * For Cloud, version is always null — Cloud has only one live version.
 *
 * @returns {Promise<{ type: 'client-managed' | 'cloud', version: string | null, codePath: string }>}
 *   Platform detection result with resolved code path.
 */
export async function detectPlatform() {
    const type = detectPlatformType();

    if (type === 'cloud') {
        logger.info('Platform detected: Qlik Cloud');
        return { type: 'cloud', version: null, codePath: 'default' };
    }

    // Client-managed — attempt version detection
    try {
        const versionInfo = await clientManaged.getSenseVersion();
        const version = versionInfo?.version ?? null;
        const codePath = clientManaged.resolveCodePath(version);

        logger.info(
            `Platform detected: Client-managed Qlik Sense v${version ?? 'unknown'} → code path "${codePath}"`
        );

        return { type: 'client-managed', version, codePath };
    } catch (err) {
        logger.warn('Version detection failed, using default code path:', err);
        return { type: 'client-managed', version: null, codePath: 'default' };
    }
}

/**
 * Get the platform adapter module.
 *
 * Returns the statically-imported adapter that matches the current platform.
 *
 * @returns {object} The platform adapter with: getCurrentSheetId, getSheetObjects,
 *   getObjectSelector, isEditMode, injectCSS
 */
export function getPlatformAdapter() {
    const type = detectPlatformType();
    return type === 'cloud' ? cloud : clientManaged;
}

/**
 * Synchronous object-selector lookup that delegates to selectors.js.
 *
 * Used by tour-runner.js and other code that needs a CSS selector string
 * without awaiting an async import.
 *
 * @param {string} platformType - 'client-managed' or 'cloud'.
 * @param {string} objectId - The Qlik object identifier.
 * @param {string} [codePath] - Code-path name from platform detection (e.g. 'default').
 * @returns {string} CSS selector string.
 */
export function getObjectSelectorSync(platformType, objectId, codePath) {
    const sels = getSelectors(platformType, codePath);
    return sels.objectById(objectId);
}
